//#############################################################################
//
// FILE:   cllc.h
//
// TITLE: This is the solution header file.
//
//#############################################################################

#ifndef CLLC_H
#define CLLC_H

#ifdef __cplusplus

extern "C" {
#endif

//
// the includes & defines
//
#include <stdint.h>
#include <stddef.h>

#include <math.h>

//
// this is the file generated by the powerSUITE page for this system
//
#include "settings.h"
#include "hal.h"

//
// Function initialize the global variables
//
void initGlobalVariables(void);

typedef union{
    enum
    {
        powerFlow_PrimToSec = POWER_FLOW_PRIM_SEC,
        powerFlow_SecToPrim = POWER_FLOW_SEC_PRIM,
        powerFlow_intermediateState = POWER_FLOW_TRANSTION_STAGE,
    }PowerFlowState_Enum;
    int32_t pad;
}PowerFlowState_EnumType;

extern  PowerFlowState_EnumType powerFlowStateActive,
                                  powerFlowState;

typedef union{
    enum
    {
        pwmSwState_disabledAll = 0,
        pwmSwState_synchronousRectification_OFF = 1,
        pwmSwState_synchronousRectification_fixedDuty = 2,
        pwmSwState_synchronousRectification_active = 3
    }PwmSwState_Enum;
    int32_t pad;
}PwmSwState_EnumType;

extern  PwmSwState_EnumType pwmSwStateActive, pwmSwState;

#endif