//#############################################################################
//
// FILE:   CLLC_user_settings.h
//
// TITLE:  clllc User Settings
//
//#############################################################################
// $TI Release: obc_7_4kw_ttplpfc_clllc v2.00.03.00 $
// $Release Date: Tue Aug 26 14:08:13 CDT 2025 $
// $Copyright:
// Copyright (C) 2025 Texas Instruments Incorporated - http://www.ti.com/
//
// ALL RIGHTS RESERVED
// $
//#############################################################################

//
// BUILD_F28004X
// BUILD_F2838X
// BUILD_F28003X
//
#define  BUILD_F28003X

#ifndef PI_VALUE
#define PI_VALUE ((float32_t)3.141592653589)
#endif

#ifndef ONE_NANO_SEC
#define ONE_NANO_SEC ((float32_t)0.000000001)
#endif

#ifndef TWO_RAISED_TO_THE_POWER_SIXTEEN
#define TWO_RAISED_TO_THE_POWER_SIXTEEN ((float32_t)65536.0)
#endif

#ifndef TICKS_IN_PWM_FREQUENCY
#define TICKS_IN_PWM_FREQUENCY(m, n) (uint32_t)(n / (float32_t)m)
#endif

#ifndef TRUE
#define FALSE 0
#define TRUE  1
#endif

//
// Active synchronous rectification enable
//
#define CLLC_ASR_ENABLE 1

//
//Transformer polarity setting
//0 = positive polarity, 1 = negative polarity
//
#define CLLC_POSITIVE_POLARITY 0
#define CLLC_NEGATIVE_POLARITY 1
#define CLLC_TRANSFORMER_POLARITY CLLC_NEGATIVE_POLARITY

//
// PWM pin, ADC, SDFM, Relay Selection related variables
//
#define CLLC_ADC_BASE_SAMPLING_FREQUENCY_HZ       ((float)120*1000)
#define CLLC_ADC_BASE_SAMPLING_PERIOD             ((CLLC_PWMSYSCLOCK_FREQ_HZ) / (CLLC_ADC_BASE_SAMPLING_FREQUENCY_HZ))
#define CLLC_ADC_TIGGER_PWM1_BASE                 EPWM6_BASE
#define CLLC_ADC_TIGGER_PWM2_BASE                 EPWM7_BASE

#define CLLC_PRIM_LEG1_PWM_BASE                   EPWM1_BASE
#define CLLC_PRIM_LEG1_PWM_NO                     1
#define CLLC_PRIM_LEG1_PWM_H_GPIO                 0
#define CLLC_PRIM_LEG1_PWM_H_GPIO_PIN_CONFIG      GPIO_0_EPWM1_A
#define CLLC_PRIM_LEG1_PWM_H_DIS_GPIO_PIN_CONFIG  GPIO_0_GPIO0
#define CLLC_PRIM_LEG1_PWM_L_GPIO                 1
#define CLLC_PRIM_LEG1_PWM_L_GPIO_PIN_CONFIG      GPIO_1_EPWM1_B
#define CLLC_PRIM_LEG1_PWM_L_DIS_GPIO_PIN_CONFIG  GPIO_1_GPIO1

#define CLLC_PRIM_LEG2_PWM_BASE                   EPWM2_BASE
#define CLLC_PRIM_LEG2_PWM_NO                     2
#define CLLC_PRIM_LEG2_PWM_H_GPIO                 2
#define CLLC_PRIM_LEG2_PWM_H_GPIO_PIN_CONFIG      GPIO_2_EPWM2_A
#define CLLC_PRIM_LEG2_PWM_H_DIS_GPIO_PIN_CONFIG  GPIO_2_GPIO2
#define CLLC_PRIM_LEG2_PWM_L_GPIO                 3
#define CLLC_PRIM_LEG2_PWM_L_GPIO_PIN_CONFIG      GPIO_3_EPWM2_B
#define CLLC_PRIM_LEG2_PWM_L_DIS_GPIO_PIN_CONFIG  GPIO_3_GPIO3

#define CLLC_SEC_LEG1_PWM_BASE                   EPWM3_BASE
#define CLLC_SEC_LEG1_PWM_NO                     3
#define CLLC_SEC_LEG1_PWM_H_GPIO                 4
#define CLLC_SEC_LEG1_PWM_H_GPIO_PIN_CONFIG      GPIO_4_EPWM3_A
#define CLLC_SEC_LEG1_PWM_H_DIS_GPIO_PIN_CONFIG  GPIO_4_GPIO4
#define CLLC_SEC_LEG1_PWM_L_GPIO                 5
#define CLLC_SEC_LEG1_PWM_L_GPIO_PIN_CONFIG      GPIO_5_EPWM3_B
#define CLLC_SEC_LEG1_PWM_L_DIS_GPIO_PIN_CONFIG  GPIO_5_GPIO5

#define CLLC_SEC_LEG2_PWM_BASE                   EPWM4_BASE
#define CLLC_SEC_LEG2_PWM_NO                     4
#define CLLC_SEC_LEG2_PWM_H_GPIO                 6
#define CLLC_SEC_LEG2_PWM_H_GPIO_PIN_CONFIG      GPIO_6_EPWM4_A
#define CLLC_SEC_LEG2_PWM_H_DIS_GPIO_PIN_CONFIG  GPIO_6_GPIO6
#define CLLC_SEC_LEG2_PWM_L_GPIO                 7
#define CLLC_SEC_LEG2_PWM_L_GPIO_PIN_CONFIG      GPIO_7_EPWM4_B
#define CLLC_SEC_LEG2_PWM_L_DIS_GPIO_PIN_CONFIG  GPIO_7_GPIO7

#define CLLC_GLOBAL_LOAD_ENABLED 0

#define CLLC_MAX_PERIOD_STEP_PU ((float32_t)0.05)

//
//ISR related
//
#define CLLC_ISR1_PERIPHERAL_TRIG_BASE CLLC_PRIM_LEG1_PWM_BASE
#define CLLC_ISR1_TRIG INT_EPWM1
#define CLLC_ISR1_PIE_GROUP INTERRUPT_ACK_GROUP3

#define CLLC_ISR1_TRIG_CLA CLA_TRIGGER_EPWM1INT

#if CLLC_ISR1_RUNNING_ON == CLA_CORE
#define CLLC_ISR2_RUNNING_ON CLA_CORE
#else
#define CLLC_ISR2_RUNNING_ON C28x_CORE
#endif

#define CLLC_ISR2_ECAP_BASE ECAP1_BASE
#define CLLC_ISR2_PWM_BASE EPWM5_BASE
#define CLLC_ISR2_TRIG INT_ECAP1
#define CLLC_ISR2_PIE_GROUP INTERRUPT_ACK_GROUP4

#define CLLC_ISR2_TRIG_CLA CLA_TRIGGER_ECAP1INT

#define CLLC_ISR3_TIMEBASE CLLC_TASKC_CPUTIMER_BASE
#define CLLC_ISR3_PERIPHERAL_TRIG_BASE ADCC_BASE
#define CLLC_ISR3_TRIG INT_ADCC2
#define CLLC_ISR3_PIE_GROUP INTERRUPT_ACK_GROUP10
//
// Compensator related
//
#define CLLC_GI_OUT_MAX   ((float32_t)0.98)
#define CLLC_GI_OUT_MIN   ((float32_t)-0.1)

#define CLLC_GV_OUT_MAX   ((float32_t)0.98)
#define CLLC_GV_OUT_MIN   ((float32_t)-0.1)

#define CLLC_VOLTS_PER_SECOND_SLEW ((float32_t)10.0)
#define CLLC_AMPS_PER_SECOND_SLEW ((float32_t)0.5)

//
//100pin control card
//

//
// 0 is disabled, 1 is enabled
//
#define CLLC_OVERSAMPLING_ENABLED   1
#define CLLC_VSEC_OVERSAMPLING_11x  1

//
// ADC triggers
//
#define CLLC_ADC_SOC_TRIG1 ADC_TRIGGER_EPWM6_SOCA
#define CLLC_ADC_SOC_TRIG2 ADC_TRIGGER_EPWM6_SOCB
#define CLLC_ADC_SOC_TRIG3 ADC_TRIGGER_EPWM7_SOCA
#define CLLC_ADC_SOC_TRIG4 ADC_TRIGGER_EPWM7_SOCB
#define CLLC_ADC_SOC_TRIG5 ADC_TRIGGER_CPU1_TINT2

#define CLLC_ADC_SOC_TRIG_CLLC_PWM_SYNC1 ADC_TRIGGER_EPWM1_SOCA
#define CLLC_ADC_SOC_TRIG_CLLC_PWM_SYNC2 ADC_TRIGGER_EPWM1_SOCB

#define CLLC_ADC_ACQPS_SYS_CLKS 30

//
// Signals mapped to ADC -A
//
#define CLLC_ISEC_ADC_MODULE           ADCA_BASE
#define CLLC_ISEC_ADC_PIN              ADC_CH_ADCIN5
#define CLLC_ISEC_ADC_ACQPS_SYS_CLKS   CLLC_ADC_ACQPS_SYS_CLKS
#define CLLC_ISEC_ADCRESULTREGBASE     ADCARESULT_BASE

#define CLLC_ISEC_ADC_TRIG_SOURCE_1    CLLC_ADC_SOC_TRIG1
#define CLLC_ISEC_ADC_TRIG_SOURCE_2    CLLC_ADC_SOC_TRIG2
//#define CLLC_ISEC_ADC_TRIG_SOURCE_3    CLLC_ADC_SOC_TRIG_CLLC_PWM_SYNC2
//#define CLLC_ISEC_ADC_TRIG_SOURCE_4    CLLC_ADC_SOC_TRIG_CLLC_PWM_SYNC2

#define CLLC_ISEC_ADC_SOC_NO_1         ADC_SOC_NUMBER2
#define CLLC_ISEC_ADC_SOC_NO_2         ADC_SOC_NUMBER3
#define CLLC_ISEC_ADC_SOC_NO_3         ADC_SOC_NUMBER4
#define CLLC_ISEC_ADC_SOC_NO_4         ADC_SOC_NUMBER5
#define CLLC_ISEC_ADC_SOC_NO_5         ADC_SOC_NUMBER6
#define CLLC_ISEC_ADC_SOC_NO_6         ADC_SOC_NUMBER7
#define CLLC_ISEC_ADC_SOC_NO_7         ADC_SOC_NUMBER8
#define CLLC_ISEC_ADC_SOC_NO_8         ADC_SOC_NUMBER9
#define CLLC_ISEC_ADC_SOC_NO_9         ADC_SOC_NUMBER10
#define CLLC_ISEC_ADC_SOC_NO_10        ADC_SOC_NUMBER11
#define CLLC_ISEC_ADC_SOC_NO_11        ADC_SOC_NUMBER12


#define CLLC_ISEC_ADCREAD_1 ADC_readResult(CLLC_ISEC_ADCRESULTREGBASE, CLLC_ISEC_ADC_SOC_NO_1)
#define CLLC_ISEC_ADCREAD_2 ADC_readResult(CLLC_ISEC_ADCRESULTREGBASE, CLLC_ISEC_ADC_SOC_NO_2)
#define CLLC_ISEC_ADCREAD_3 ADC_readResult(CLLC_ISEC_ADCRESULTREGBASE, CLLC_ISEC_ADC_SOC_NO_3)
#define CLLC_ISEC_ADCREAD_4 ADC_readResult(CLLC_ISEC_ADCRESULTREGBASE, CLLC_ISEC_ADC_SOC_NO_4)
#define CLLC_ISEC_ADCREAD_5 ADC_readResult(CLLC_ISEC_ADCRESULTREGBASE, CLLC_ISEC_ADC_SOC_NO_5)
#define CLLC_ISEC_ADCREAD_6 ADC_readResult(CLLC_ISEC_ADCRESULTREGBASE, CLLC_ISEC_ADC_SOC_NO_6)
#define CLLC_ISEC_ADCREAD_7 ADC_readResult(CLLC_ISEC_ADCRESULTREGBASE, CLLC_ISEC_ADC_SOC_NO_7)
#define CLLC_ISEC_ADCREAD_8 ADC_readResult(CLLC_ISEC_ADCRESULTREGBASE, CLLC_ISEC_ADC_SOC_NO_8)
#define CLLC_ISEC_ADCREAD_9 ADC_readResult(CLLC_ISEC_ADCRESULTREGBASE, CLLC_ISEC_ADC_SOC_NO_9)
#define CLLC_ISEC_ADCREAD_10 ADC_readResult(CLLC_ISEC_ADCRESULTREGBASE, CLLC_ISEC_ADC_SOC_NO_10)
#define CLLC_ISEC_ADCREAD_11 ADC_readResult(CLLC_ISEC_ADCRESULTREGBASE, CLLC_ISEC_ADC_SOC_NO_11)


//
// Signals mapped to ADC -B
//
#define CLLC_VPRIM_ADC_MODULE          ADCB_BASE
#define CLLC_VPRIM_ADC_PIN             ADC_CH_ADCIN4
#define CLLC_VPRIM_ADC_ACQPS_SYS_CLKS  CLLC_ADC_ACQPS_SYS_CLKS
#define CLLC_VPRIM_ADCRESULTREGBASE    ADCBRESULT_BASE

#define CLLC_VPRIM_ADC_TRIG_SOURCE_1   CLLC_ADC_SOC_TRIG1
#define CLLC_VPRIM_ADC_TRIG_SOURCE_2   CLLC_ADC_SOC_TRIG2
#define CLLC_VPRIM_ADC_TRIG_SOURCE_3   CLLC_ADC_SOC_TRIG3
#define CLLC_VPRIM_ADC_TRIG_SOURCE_4   CLLC_ADC_SOC_TRIG4

#define CLLC_VPRIM_ADC_SOC_NO_1        ADC_SOC_NUMBER2
#define CLLC_VPRIM_ADC_SOC_NO_2        ADC_SOC_NUMBER3
#define CLLC_VPRIM_ADC_SOC_NO_3        ADC_SOC_NUMBER4
#define CLLC_VPRIM_ADC_SOC_NO_4        ADC_SOC_NUMBER5

#define CLLC_VPRIM_ADCREAD_1 ADC_readResult(CLLC_VPRIM_ADCRESULTREGBASE, CLLC_VPRIM_ADC_SOC_NO_1)
#define CLLC_VPRIM_ADCREAD_2 ADC_readResult(CLLC_VPRIM_ADCRESULTREGBASE, CLLC_VPRIM_ADC_SOC_NO_2)
#define CLLC_VPRIM_ADCREAD_3 ADC_readResult(CLLC_VPRIM_ADCRESULTREGBASE, CLLC_VPRIM_ADC_SOC_NO_3)
#define CLLC_VPRIM_ADCREAD_4 ADC_readResult(CLLC_VPRIM_ADCRESULTREGBASE, CLLC_VPRIM_ADC_SOC_NO_4)

//
// Signals mapped to ADC -B
//
#define CLLC_VSEC_ADC_MODULE           ADCC_BASE
#define CLLC_VSEC_ADC_PIN              ADC_CH_ADCIN11
#define CLLC_VSEC_ADC_ACQPS_SYS_CLKS   CLLC_ADC_ACQPS_SYS_CLKS
#define CLLC_VSEC_ADCRESULTREGBASE     ADCCRESULT_BASE

#define CLLC_VSEC_ADC_TRIG_SOURCE_1    CLLC_ADC_SOC_TRIG1
#define CLLC_VSEC_ADC_TRIG_SOURCE_2    CLLC_ADC_SOC_TRIG2
//#define CLLC_VSEC_ADC_TRIG_SOURCE_3    CLLC_ADC_SOC_TRIG_CLLC_PWM_SYNC2
//#define CLLC_VSEC_ADC_TRIG_SOURCE_4    CLLC_ADC_SOC_TRIG_CLLC_PWM_SYNC2

#define CLLC_VSEC_ADC_SOC_NO_1         ADC_SOC_NUMBER2
#define CLLC_VSEC_ADC_SOC_NO_2         ADC_SOC_NUMBER3
#define CLLC_VSEC_ADC_SOC_NO_3         ADC_SOC_NUMBER4
#define CLLC_VSEC_ADC_SOC_NO_4         ADC_SOC_NUMBER5
#define CLLC_VSEC_ADC_SOC_NO_5         ADC_SOC_NUMBER6
#define CLLC_VSEC_ADC_SOC_NO_6         ADC_SOC_NUMBER7
#define CLLC_VSEC_ADC_SOC_NO_7         ADC_SOC_NUMBER8
#define CLLC_VSEC_ADC_SOC_NO_8         ADC_SOC_NUMBER9
#define CLLC_VSEC_ADC_SOC_NO_9        ADC_SOC_NUMBER10
#define CLLC_VSEC_ADC_SOC_NO_10        ADC_SOC_NUMBER11
#define CLLC_VSEC_ADC_SOC_NO_11        ADC_SOC_NUMBER12


#define CLLC_VSEC_ADC_SOC_NO_13        ADC_SOC_NUMBER15

#define CLLC_VSEC_ADCREAD_1  ADC_readResult(CLLC_VSEC_ADCRESULTREGBASE, CLLC_VSEC_ADC_SOC_NO_1)
#define CLLC_VSEC_ADCREAD_2  ADC_readResult(CLLC_VSEC_ADCRESULTREGBASE, CLLC_VSEC_ADC_SOC_NO_2)
#define CLLC_VSEC_ADCREAD_3  ADC_readResult(CLLC_VSEC_ADCRESULTREGBASE, CLLC_VSEC_ADC_SOC_NO_3)
#define CLLC_VSEC_ADCREAD_4  ADC_readResult(CLLC_VSEC_ADCRESULTREGBASE, CLLC_VSEC_ADC_SOC_NO_4)
#define CLLC_VSEC_ADCREAD_5  ADC_readResult(CLLC_VSEC_ADCRESULTREGBASE, CLLC_VSEC_ADC_SOC_NO_5)
#define CLLC_VSEC_ADCREAD_6  ADC_readResult(CLLC_VSEC_ADCRESULTREGBASE, CLLC_VSEC_ADC_SOC_NO_6)
#define CLLC_VSEC_ADCREAD_7  ADC_readResult(CLLC_VSEC_ADCRESULTREGBASE, CLLC_VSEC_ADC_SOC_NO_7)
#define CLLC_VSEC_ADCREAD_8  ADC_readResult(CLLC_VSEC_ADCRESULTREGBASE, CLLC_VSEC_ADC_SOC_NO_8)
#define CLLC_VSEC_ADCREAD_9  ADC_readResult(CLLC_VSEC_ADCRESULTREGBASE, CLLC_VSEC_ADC_SOC_NO_9)
#define CLLC_VSEC_ADCREAD_10 ADC_readResult(CLLC_VSEC_ADCRESULTREGBASE, CLLC_VSEC_ADC_SOC_NO_10)
#define CLLC_VSEC_ADCREAD_11 ADC_readResult(CLLC_VSEC_ADCRESULTREGBASE, CLLC_VSEC_ADC_SOC_NO_11)


//
// Signals mapped to ADC -A
//
#define CLLC_IPRIM_ADC_MODULE          ADCA_BASE
#define CLLC_IPRIM_ADC_PIN             ADC_CH_ADCIN9
#define CLLC_IPRIM_ADC_ACQPS_SYS_CLKS  CLLC_ADC_ACQPS_SYS_CLKS
#define CLLC_IPRIM_ADCRESULTREGBASE    ADCARESULT_BASE
#define CLLC_IPRIM_ADC_TRIG_SOURCE     CLLC_ADC_SOC_TRIG_CLLC_PWM_SYNC1
#define CLLC_IPRIM_ADC_SOC_NO          ADC_SOC_NUMBER13
#define CLLC_IPRIM_ADCREAD ADC_readResult(CLLC_IPRIM_ADCRESULTREGBASE, CLLC_IPRIM_ADC_SOC_NO)

//
// Macros for reading the ADCs
//
#define CLLC_VPRIM_ADCREAD (CLLC_VPRIM_ADCREAD_1)

#if CLLC_OVERSAMPLING_ENABLED == 1
//
// 4x oversample
//
    // #define CLLC_VPRIM_OVERSAMPLE_ADCREAD ((CLLC_VPRIM_ADCREAD_1 + CLLC_VPRIM_ADCREAD_2 + CLLC_VPRIM_ADCREAD_3 + CLLC_VPRIM_ADCREAD_4) * (0.25))

//
// 2x oversample
//
       #define CLLC_VPRIM_OVERSAMPLE_ADCREAD ((CLLC_VPRIM_ADCREAD_1 + CLLC_VPRIM_ADCREAD_2 ) * (0.5f))
#endif

#define CLLC_VSEC_ADCREAD (CLLC_VSEC_ADCREAD_1)

#if CLLC_OVERSAMPLING_ENABLED == 1
    #if CLLC_VSEC_OVERSAMPLING_11x == 1
        #define CLLC_VSEC_OVERSAMPLE_ADCREAD ((CLLC_VSEC_ADCREAD_1 + CLLC_VSEC_ADCREAD_2 + CLLC_VSEC_ADCREAD_3 + CLLC_VSEC_ADCREAD_4 + CLLC_VSEC_ADCREAD_5 + CLLC_VSEC_ADCREAD_6 + CLLC_VSEC_ADCREAD_7 + CLLC_VSEC_ADCREAD_8 + CLLC_VSEC_ADCREAD_9 + CLLC_VSEC_ADCREAD_10 + CLLC_VSEC_ADCREAD_11 ) * (0.0909090))
    #else
//
// 4x oversample
//

//        #define CLLC_VSEC_OVERSAMPLE_ADCREAD ((CLLC_VSEC_ADCREAD_1 + CLLC_VSEC_ADCREAD_2 + CLLC_VSEC_ADCREAD_3 + CLLC_VSEC_ADCREAD_4) * (0.25))

//
// 2x oversample
//
         #define CLLC_VSEC_OVERSAMPLE_ADCREAD ((CLLC_VSEC_ADCREAD_1 + CLLC_VSEC_ADCREAD_2) * (0.5f))
    #endif
#endif

#define CLLC_ISEC_ADCREAD (CLLC_ISEC_ADCREAD_1)

#if CLLC_OVERSAMPLING_ENABLED == 1
#if CLLC_VSEC_OVERSAMPLING_11x == 1
    //
    // 12x oversample
    //
    #define CLLC_ISEC_OVERSAMPLE_ADCREAD ((CLLC_ISEC_ADCREAD_1 + CLLC_ISEC_ADCREAD_2 + CLLC_ISEC_ADCREAD_3 + CLLC_ISEC_ADCREAD_4 + CLLC_ISEC_ADCREAD_5 + CLLC_ISEC_ADCREAD_6 + CLLC_ISEC_ADCREAD_7 + CLLC_ISEC_ADCREAD_8 + CLLC_ISEC_ADCREAD_9 + CLLC_ISEC_ADCREAD_10 + CLLC_ISEC_ADCREAD_11 ) * (0.0909090))
#else
//
// 4x oversample
//
//    #define CLLC_ISEC_OVERSAMPLE_ADCREAD ((CLLC_ISEC_ADCREAD_1 + CLLC_ISEC_ADCREAD_2 + CLLC_ISEC_ADCREAD_3 + CLLC_ISEC_ADCREAD_4) * (0.25))

//
// 2x oversample
//
    #define CLLC_ISEC_OVERSAMPLE_ADCREAD ((CLLC_ISEC_ADCREAD_1 + CLLC_ISEC_ADCREAD_2) * (0.5f))
#endif
#endif

#if CLLC_PROTECTION == CLLC_PROTECTION_ENABLED
//
// set 1 to enable the appropriate protection scheme
//
#define CLLC_BOARD_PROTECTION_IPRIM 0
#define CLLC_BOARD_PROTECTION_ISEC 0
#define CLLC_BOARD_PROTECTION_VSEC 0
#define CLLC_BOARD_PROTECTION_GANFAULT 1
#else
//
// set 0 to disable the appropriate protection scheme
//
#define CLLC_BOARD_PROTECTION_IPRIM 0
#define CLLC_BOARD_PROTECTION_ISEC 0
#define CLLC_BOARD_PROTECTION_VSEC 0
#define CLLC_BOARD_PROTECTION_GANFAULT 0
#endif

#define CLLC_IPRIM_CMPSS_BASE CMPSS2_BASE
#define CLLC_IPRIM_CMPSS_XBAR_MUX XBAR_MUX02
#define CLLC_IPRIM_CMPSS_XBAR_MUX_VAL XBAR_EPWM_MUX02_CMPSS2_CTRIPH_OR_L
#define CLLC_IPRIM_CMPSS_ASYSCTRL_CMPHPMUX ASYSCTL_CMPHPMUX_SELECT_2
#define CLLC_IPRIM_CMPSS_ASYSCTRL_CMPLPMUX ASYSCTL_CMPLPMUX_SELECT_2
#define CLLC_IPRIM_CMPSS_ASYSCTRL_MUX_VALUE 2
#define CLLC_IPRIM_CMPSS_XBAR_FLAG1 XBAR_INPUT_FLG_CMPSS2_CTRIPH
#define CLLC_IPRIM_CMPSS_XBAR_FLAG2 XBAR_INPUT_FLG_CMPSS2_CTRIPL

#define CLLC_ISEC_CMPSS_BASE CMPSS2_BASE
#define CLLC_ISEC_XBAR_MUX XBAR_MUX02
#define CLLC_ISEC_XBAR_MUX_VAL XBAR_EPWM_MUX02_CMPSS2_CTRIPH_OR_L
#define CLLC_ISEC_CMPSS_ASYSCTRL_CMPHPMUX ASYSCTL_CMPHPMUX_SELECT_2
#define CLLC_ISEC_CMPSS_ASYSCTRL_CMPLPMUX ASYSCTL_CMPLPMUX_SELECT_2
#define CLLC_ISEC_CMPSS_ASYSCTRL_MUX_VALUE 5
#define CLLC_ISEC_CMPSS_XBAR_FLAG1 XBAR_INPUT_FLG_CMPSS2_CTRIPH
#define CLLC_ISEC_CMPSS_XBAR_FLAG2 XBAR_INPUT_FLG_CMPSS2_CTRIPL

#define CLLC_VSEC_CMPSS_BASE CMPSS2_BASE
#define CLLC_VSEC_CMPSS_XBAR_MUX XBAR_MUX02
#define CLLC_VSEC_CMPSS_ASYSCTRL_CMPHPMUX ASYSCTL_CMPHPMUX_SELECT_2
#define CLLC_VSEC_CMPSS_ASYSCTRL_CMPLPMUX ASYSCTL_CMPLPMUX_SELECT_2
#define CLLC_VSEC_CMPSS_ASYSCTRL_MUX_VALUE 4
#define CLLC_VSEC_CMPSS_XBAR_MUX_VAL XBAR_EPWM_MUX02_CMPSS2_CTRIPH
#define CLLC_VSEC_CMPSS_XBAR_FLAG1 XBAR_INPUT_FLG_CMPSS2_CTRIPH


#define CLLC_ISEC_TANK_CMPSS_BASE CMPSS4_BASE
#define CLLC_ISEC_TANK_H_XBAR_MUX XBAR_MUX06
#define CLLC_ISEC_TANK_CMPSS_ASYSCTRL_CMPHPMUX ASYSCTL_CMPHPMUX_SELECT_4
#define CLLC_ISEC_TANK_CMPSS_ASYSCTRL_CMPLPMUX ASYSCTL_CMPLPMUX_SELECT_4
#define CLLC_ISEC_TANK_CMPSS_ASYSCTRL_MUX_VALUE 2
#define CLLC_ISEC_TANK_H_PWM_XBAR_MUX_VAL XBAR_EPWM_MUX06_CMPSS4_CTRIPH
#define CLLC_ISEC_TANK_H_OUT_XBAR_MUX_VAL XBAR_OUT_MUX06_CMPSS4_CTRIPOUTH

#define CLLC_ISEC_TANK_L_XBAR_MUX XBAR_MUX07
#define CLLC_ISEC_TANK_L_PWM_XBAR_MUX_VAL XBAR_EPWM_MUX07_CMPSS4_CTRIPL
#define CLLC_ISEC_TANK_L_OUT_XBAR_MUX_VAL XBAR_OUT_MUX07_CMPSS4_CTRIPOUTL

#define CLLC_ISEC_TANK_H_CMPSS_XBAR_FLAG XBAR_INPUT_FLG_CMPSS4_CTRIPH
#define CLLC_ISEC_TANK_L_CMPSS_XBAR_FLAG XBAR_INPUT_FLG_CMPSS4_CTRIPL

//
// Set DAC H to 2150 and L to 1950
// This is done by emperical tuning of the board for efficiency
//
#define CLLC_ISEC_TANK_DACHVAL 2100
#define CLLC_ISEC_TANK_DACLVAL 2000

//
// IPRIM TANK
//
#define CLLC_IPRIM_TANK_CMPSS_BASE CMPSS2_BASE
#define CLLC_IPRIM_TANK_CMPSS_XBAR_FLAG1 XBAR_INPUT_FLG_CMPSS2_CTRIPH
#define CLLC_IPRIM_TANK_CMPSS_XBAR_FLAG2 XBAR_INPUT_FLG_CMPSS2_CTRIPL

#define CLLC_IPRIM_TANK_H_XBAR_MUX XBAR_MUX02
#define CLLC_IPRIM_TANK_H_PWM_XBAR_MUX_VAL XBAR_EPWM_MUX02_CMPSS2_CTRIPH
#define CLLC_IPRIM_TANK_H_OUT_XBAR_MUX_VAL XBAR_OUT_MUX02_CMPSS2_CTRIPOUTH

#define CLLC_IPRIM_TANK_L_XBAR_MUX XBAR_MUX03
#define CLLC_IPRIM_TANK_L_PWM_XBAR_MUX_VAL XBAR_EPWM_MUX03_CMPSS2_CTRIPL
#define CLLC_IPRIM_TANK_L_OUT_XBAR_MUX_VAL XBAR_OUT_MUX03_CMPSS2_CTRIPOUTL



//
// Set DAC H to 2150 and L to 1950
// This is done by emperical tuning of the board for efficiency
//
#define CLLC_IPRIM_TANK_DACHVAL 2150
#define CLLC_IPRIM_TANK_DACLVAL 1950


//// Debug related
//// Active synchronous rectification debug, can only be used when Profiling is disabled.
////
//#define CLLC_GPIO_XBAR1                      44
//#define CLLC_GPIO_XBAR1_PIN_CONFIG           GPIO_44_OUTPUTXBAR7
//
//#define CLLC_GPIO_XBAR2                      49
//#define CLLC_GPIO_XBAR2_PIN_CONFIG           GPIO_49_OUTPUTXBAR4

//
// GPIO profiling
//

#define CLLC_GPIO_PROFILING1 40
#define CLLC_GPIO_PROFILING1_SET_REG GPIO_O_GPBSET
#define CLLC_GPIO_PROFILING1_CLEAR_REG GPIO_O_GPBCLEAR
#define CLLC_GPIO_PROFILING1_SET GPIO_GPBSET_GPIO40
#define CLLC_GPIO_PROFILING1_CLEAR GPIO_GPBCLEAR_GPIO40
#define CLLC_GPIO_PROFILING1_PIN_CONFIG GPIO_40_GPIO40

#define CLLC_GPIO_PROFILING2 44
#define CLLC_GPIO_PROFILING2_SET_REG GPIO_O_GPBSET
#define CLLC_GPIO_PROFILING2_CLEAR_REG GPIO_O_GPBCLEAR
#define CLLC_GPIO_PROFILING2_SET GPIO_GPBSET_GPIO44
#define CLLC_GPIO_PROFILING2_CLEAR GPIO_GPBCLEAR_GPIO44
#define CLLC_GPIO_PROFILING2_PIN_CONFIG GPIO_44_GPIO44

//
// Reuse FSI reserved pin for CLLC_GPIO_PROFILING3 and CLLC_GPIO_STEPCHANGEFREQ
//
#define CLLC_GPIO_PROFILING3 49
#define CLLC_GPIO_PROFILING3_SET_REG GPIO_O_GPBSET
#define CLLC_GPIO_PROFILING3_CLEAR_REG GPIO_O_GPBCLEAR
#define CLLC_GPIO_PROFILING3_SET GPIO_GPBSET_GPIO49
#define CLLC_GPIO_PROFILING3_CLEAR GPIO_GPBCLEAR_GPIO49
#define CLLC_GPIO_PROFILING3_PIN_CONFIG GPIO_49_GPIO49


#define CLLC_GPIO_STEPCHANGEFREQ 50
#define CLLC_GPIO_STEPCHANGEFREQ_SET_REG GPIO_O_GPBSET
#define CLLC_GPIO_STEPCHANGEFREQ_CLEAR_REG GPIO_O_GPBCLEAR
#define CLLC_GPIO_STEPCHANGEFREQ_SET GPIO_GPBSET_GPIO50
#define CLLC_GPIO_STEPCHANGEFREQ_CLEAR GPIO_GPBCLEAR_GPIO50
#define CLLC_GPIO_STEPCHANGEFREQ_PIN_CONFIG GPIO_50_GPIO50


//
// ECAP Temperature reading
//
#define CLLC_TEMP_OVERSAMPLE 1024
#define CLLC_TEMP_CHAN 12

#define CLLC_GPIO_TEMP_MUX_OUT1 41
#define CLLC_GPIO_TEMP_MUX_OUT1_PIN_CONFIG GPIO_41_GPIO41//todo check all TEMP reading GPIOs
#define CLLC_TEMP_MUX_OUT1_ECAP_BASE  ECAP2_BASE
#define CLLC_TEMP_MUX_OUT1_INPUTXBAR  XBAR_INPUT3
#define CLLC_TEMP_MUX_OUT1_ECAP_INPUT ECAP_INPUT_INPUTXBAR3

#define CLLC_GPIO_TEMP_MUX_OUT2 60
#define CLLC_GPIO_TEMP_MUX_OUT2_PIN_CONFIG GPIO_60_GPIO60
#define CLLC_TEMP_MUX_OUT2_ECAP_BASE  ECAP3_BASE
#define CLLC_TEMP_MUX_OUT2_INPUTXBAR  XBAR_INPUT4
#define CLLC_TEMP_MUX_OUT2_ECAP_INPUT ECAP_INPUT_INPUTXBAR4

#define CLLC_GPIO_TEMP_MUX_SEL0 47
#define CLLC_GPIO_TEMP_MUX_SEL0_PIN_CONFIG GPIO_47_GPIO47

#define CLLC_GPIO_TEMP_MUX_SEL1 58
#define CLLC_GPIO_TEMP_MUX_SEL1_PIN_CONFIG GPIO_58_GPIO58

#define CLLC_GPIO_TEMP_MUX_SEL2 59
#define CLLC_GPIO_TEMP_MUX_SEL2_PIN_CONFIG GPIO_59_GPIO59

//
// LED blink
//
#define CLLC_GPIO_LED1 34
#define CLLC_GPIO_LED1_SET GPIO_GPBSET_GPIO34
#define CLLC_GPIO_LED1_CLEAR GPIO_GPBCLEAR_GPIO34
#define CLLC_GPIO_LED1_PIN_CONFIG GPIO_34_GPIO34

//
// Commutation Inductor control
//
#define CLLC_GPIO_LC 14
#define CLLC_GPIO_LC_SET GPIO_GPASET_GPIO14
#define CLLC_GPIO_LC_CLEAR GPIO_GPACLEAR_GPIO34
#define CLLC_GPIO_LC_PIN_CONFIG GPIO_34_GPIO34

//
// GaN fault trip pin
//
#define CLLC_GANFAULTn_GPIO 23
#define CLLC_GANFAULTn_GPIO_PIN_CONFIG GPIO_23_GPIO23
#define CLLC_GANFAULTn_XBAR_BASE INPUTXBAR_BASE
#define CLLC_GANFAULTn_XBAR_INPUT XBAR_INPUT2
#define CLLC_GANFAULTn_EPWM_FLAG EPWM_TZ_OST_FLAG_OST2

//
// CLLLC Secondary Sense Diagnostic Pin
//
#define CLLC_GPIO_SECSENSEDIAG 30
#define CLLC_GPIO_SECSENSEDIAG_PIN_CONFIG GPIO_30_GPIO30

//
// Add any system specific setting below
//
#define CLLC_SFRA_FREQ_START 50
#define CLLC_SFRA_FREQ_LENGTH 100
//
// SFRA step Multiply = 10^(1/No of steps per decade(40))
//
#define CLLC_SFRA_FREQ_STEP_MULTIPLY (float32_t)1.06


//
// SFRA related
//
#define CLLC_SFRA_GUI_SCI_BASE SCIA_BASE
#define CLLC_SCI_VBUS_CLK 50000000
#define CLLC_SFRA_GUI_SCI_BAUDRATE 57600

#define CLLC_SFRA_GUI_SCIRX_GPIO 28
#define CLLC_SFRA_GUI_SCITX_GPIO 29

#define CLLC_SFRA_GUI_SCIRX_GPIO_PIN_CONFIG GPIO_28_SCIA_RX
#define CLLC_SFRA_GUI_SCITX_GPIO_PIN_CONFIG GPIO_29_SCIA_TX

//
// if the following #define is set to 1 SFRA GUI indicates status on an LED
// otherwise LED code is ignored
//
#define CLLC_SFRA_GUI_LED_INDICATOR 1
#define CLLC_SFRA_GUI_LED_GPIO 31
#define CLLC_SFRA_GUI_LED_GPIO_PIN_CONFIG GPIO_31_GPIO31

//
// ADC Related
//
#define CLLC_ADC_PU_SCALE_FACTOR  ((float32_t)0.000244140625)
#define CLLC_ADC_PU_PPB_SCALE_FACTOR ((float32_t)0.000488281250) //1/2^11

#define CLLC_CMPSS_HYSTERESIS 2
#define CLLC_CMPSSS_FILTER_PRESCALAR 2
#define CLLC_CMPSS_WINODW 10
#define CLLC_CMPSS_THRESHOLD 7

//
//CPU time related
//
#define CLLC_TASKA_CPUTIMER_BASE CPUTIMER0_BASE
#define CLLC_TASKB_CPUTIMER_BASE CPUTIMER1_BASE
#define CLLC_TASKC_CPUTIMER_BASE CPUTIMER2_BASE

#define CLLC_TASKA_FREQ_HZ 100
#define CLLC_TASKB_FREQ_HZ 10
#define CLLC_TASKC_FREQ_HZ CLLC_ISR3_FREQUENCY_HZ

#define CLLC_GET_TASKA_TIMER_OVERFLOW_STATUS CPUTimer_getTimerOverflowStatus(CLLC_TASKA_CPUTIMER_BASE)
#define CLLC_CLEAR_TASKA_TIMER_OVERFLOW_FLAG CPUTimer_clearOverflowFlag(CLLC_TASKA_CPUTIMER_BASE)

#define CLLC_GET_TASKB_TIMER_OVERFLOW_STATUS CPUTimer_getTimerOverflowStatus(CLLC_TASKB_CPUTIMER_BASE)
#define CLLC_CLEAR_TASKB_TIMER_OVERFLOW_FLAG CPUTimer_clearOverflowFlag(CLLC_TASKB_CPUTIMER_BASE)

//
// Profiling related
//
#define CLLC_PROFILING1_INPUTXBAR          XBAR_INPUT15
#define CLLC_PROFILING2_INPUTXBAR          XBAR_INPUT16

#define CLLC_PROFILING1_ECAP               ECAP2_BASE
#define CLLC_PROFILING2_ECAP               ECAP3_BASE

#define CLLC_PROFILING1_ECAP_XBAR_MUX      ECAP_INPUT_INPUTXBAR15
#define CLLC_PROFILING2_ECAP_XBAR_MUX      ECAP_INPUT_INPUTXBAR16

#define CLLC_DAC_BASE DACB_BASE


//
// Datalogger enable
//    0: disabled
//    1: enabled
//
#define CLLC_DATALOGGER_ENABLE 0

#ifdef BUILD_F28003X
#if CLLC_BOARD_PROTECTION_IPRIM == 1 ||  CLLC_BOARD_PROTECTION_ISEC == 1 || CLLC_BOARD_PROTECTION_VSEC == 1
    #warning CMPSS2 resource conflict with IPRIM_tank
#endif
#endif
//
// End of File
//
